apiVersion: v1
kind: Service
metadata:
  name: cloud7-employeeapp-database-service
  labels:
    name: cloud7-employeeapp-database-service
spec:
  ports:
  - port: 3306
  selector:
    name: cloud7-employeeapp-database-deployment
  type: ClusterIP

