apiVersion: v1
kind: Pod
metadata:
  name: k8s-mysql
  labels:
    name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret
          key: PASSWORD
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: DBNAME
    ports:
    - name: mysql
      containerPort: 3306
      protocol: TCP

    volumeMounts:
        - name: mysql-persistent-storage
          mountPath: "/var/lib/mysql"

  volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim